### ISSUE TITLE
Question about algorithm choice

### ISSUE THREAD

**Issue by PeteDevoy** [gmarty/SCD.js#1]
Hi, this is really nice :) Single responsibility and annotated for the closure compiler, just what I like!

I would like to hack together a subtitle editor (open source) which uses SCD to generate snapping points and am thinking I may extend what you have done here with an 'algorithm' option and experiment with different detection methods.

Please could you let me know if am I correct in thinking the technique you used is what [this paper](http://ieeexplore.ieee.org/xpls/icp.jsp?arnumber=1465369&tag=1) describes in the introduction as "MAFD"? I.e.:

![MAFD](https://user-images.githubusercontent.com/4375326/28579656-237196e8-7155-11e7-9f88-bf44f22da890.png)

It would give me some confidence as better with code than I am with mathematical notation :rofl:

**Comment by gmarty** [comment]
Hey, thanks for your interest.

I read a couple of papers when working on it, but not the one you mentioned.
I developed this method mainly by trial and error, so I didn't port any specific algorithm from a paper. So, no this is not the method I used, even if it's similar.

**Comment by PeteDevoy** [comment]
Ah, okay!  Thanks for your reply.

If I do manage to implement an algorithm option would you like me to create a pull request?

**Comment by gmarty** [comment]
Yes, that'd be lovely!

**Comment by PeteDevoy** [comment]
:+1:
